import dotenv from "dotenv";

dotenv.config();

// DB
const DATABASE_URL = process.env.DATABASE_URL;

// REDIS URL
const REDIS_URL = process.env.REDIS_URL || "redis://localhost:6380";

// ACCESS TOKEN AND COOKIE
const ACCESS_TOKEN_SECRET = process.env.ACCESS_TOKEN_SECRET;
const ACCESS_TOKEN_EXPIRY = process.env.ACCESS_TOKEN_EXPIRY;
const ACCESS_COOKIE_MAX_AGE = process.env.ACCESS_COOKIE_MAX_AGE;

// REFRESH TOKEN AND COOKIE
const REFRESH_TOKEN_EXPIRY = process.env.REFRESH_TOKEN_EXPIRY;
const REFRESH_COOKIE_MAX_AGE = process.env.REFRESH_COOKIE_MAX_AGE;
const REFRESH_TOKEN_SECRET = process.env.REFRESH_TOKEN_SECRET;

// HASH SALT
const SALT_ROUNDS = Number(process.env.SALT_ROUNDS) || 12;

// SERVER OPTIONS
const PORT = Number(process.env.PORT) || 9000;
const NODE_ENV = process.env.NODE_ENV || "development";
const CLIENT_ORIGIN = process.env.CLIENT_ORIGIN || "http://localhost:5173";
const SERVER_ORIGIN = process.env.SERVER_ORIGIN;

// EMAIL VERIFICATIONS
const SENDER_PASS = process.env.SENDER_PASS;


// BREVO VERIFICATIONS
const SMTP_PASS = process.env.SMTP_PASS;
const SMTP_USER = process.env.SMTP_USER;
const SENDER_EMAIL = process.env.SENDER_EMAIL;

// CLOUDINARY
const CLOUDINARY_API_SECRET = process.env.CLOUDINARY_API_SECRET;
const CLOUDINARY_API_KEY = process.env.CLOUDINARY_API_KEY;
const CLOUDINARY_CLOUD_NAME = process.env.CLOUDINARY_CLOUD_NAME;

// PAYMENT VERIFICATION
const PAYMENT_API_KEY = process.env.PAYMENT_API_KEY;



export const Env = {
  DATABASE_URL,
  REDIS_URL,
  
  ACCESS_TOKEN_SECRET,
  ACCESS_TOKEN_EXPIRY,
  ACCESS_COOKIE_MAX_AGE,
  
  REFRESH_TOKEN_SECRET,
  REFRESH_TOKEN_EXPIRY,
  REFRESH_COOKIE_MAX_AGE,
  
  SALT_ROUNDS,
  
  PORT,
  NODE_ENV,
  CLIENT_ORIGIN,
  SERVER_ORIGIN,
  
  SENDER_EMAIL,
  SMTP_USER,
  SMTP_PASS,
  
  CLOUDINARY_CLOUD_NAME,
  CLOUDINARY_API_KEY,
  CLOUDINARY_API_SECRET,
  
  PAYMENT_API_KEY
}