import dotenv from "dotenv";

dotenv.config();

// DB
const DATABASE_URL = process.env.DATABASE_URL;

// REDIS URL
const REDIS_URL = process.env.REDIS_URL || "redis://localhost:6379";

// ACCESS TOKEN AND COOKIE
const ACCESS_TOKEN_SECRET = process.env.ACCESS_TOKEN_SECRET;
const ACCESS_TOKEN_EXPIRY = process.env.ACCESS_TOKEN_EXPIRY;
const ACCESS_COOKIE_MAX_AGE = process.env.ACCESS_COOKIE_MAX_AGE;

// REFRESH TOKEN AND COOKIE
const REFRESH_TOKEN_EXPIRY = process.env.REFRESH_TOKEN_EXPIRY;
const REFRESH_COOKIE_MAX_AGE = process.env.REFRESH_COOKIE_MAX_AGE;
const REFRESH_TOKEN_SECRET = process.env.REFRESH_TOKEN_SECRET;

// HASH SALT
const SALT_ROUNDS = Number(process.env.SALT_ROUNDS) || 12;

// SERVER OPTIONS
const PORT = Number(process.env.PORT) || 9000;
const NODE_ENV = process.env.NODE_ENV || "development";
const CLIENT_ORIGIN = process.env.CLIENT_ORIGIN || "http://localhost:5173";
const SERVER_ORIGIN = process.env.SERVER_ORIGIN;

// EMAIL VERIFICATIONS
const SENDER_PASS = process.env.SENDER_PASS;


// BREVO VERIFICATIONS
const SMTP_PASS = process.env.SMTP_PASS;
const SMTP_USER = process.env.SMTP_USER;
const SENDER_EMAIL = process.env.SENDER_EMAIL;

// brevoNODEMAILER TEST EMAIL 
const TEST_USER = process.env.TEST_USER;
const TEST_PASS = process.env.TEST_PASS;

// CLOUDINARY
const CLOUDINARY_API_SECRET = process.env.CLOUDINARY_API_SECRET;
const CLOUDINARY_API_KEY = process.env.CLOUDINARY_API_KEY;
const CLOUDINARY_CLOUD_NAME = process.env.CLOUDINARY_CLOUD_NAME;

// PAYMENT VERIFICATION
const PAYMENT_API_KEY = process.env.PAYMENT_API_KEY;

// SEED DATA AMOUNTS
const SEED_USERS = Number(process.env.SEED_USERS) || 100;
const SEED_PRODUCTS = Number(process.env.SEED_PRODUCTS) || 200;
const SEED_ADDRESSES = Number(process.env.SEED_ADDRESSES) || 200;
const SEED_ORDERS = Number(process.env.SEED_ORDERS) || 100;
const SEED_ORDER_ITEMS = Number(process.env.SEED_ORDER_ITEMS) || 500;
const SEED_PAYMENTS = Number(process.env.SEED_PAYMENTS) || 100;
const SEED_REVIEWS = Number(process.env.SEED_REVIEWS) || 1000;
const SEED_CART_ITEMS = Number(process.env.SEED_CART_ITEMS) || 500;
const SEED_NOTIFICATIONS = Number(process.env.SEED_NOTIFICATIONS) || 100;
const SEED_EXPO_TOKENS = Number(process.env.SEED_EXPO_TOKENS) || 100;
const SEED_REFRESH_TOKENS = Number(process.env.SEED_REFRESH_TOKENS) || 100;
const SEED_OTPs = Number(process.env.SEED_OTPs) || 100;



export const Env = {
  DATABASE_URL,
  REDIS_URL,
  
  ACCESS_TOKEN_SECRET,
  ACCESS_TOKEN_EXPIRY,
  ACCESS_COOKIE_MAX_AGE,
  
  REFRESH_TOKEN_SECRET,
  REFRESH_TOKEN_EXPIRY,
  REFRESH_COOKIE_MAX_AGE,
  
  SALT_ROUNDS,
  
  PORT,
  NODE_ENV,
  CLIENT_ORIGIN,
  SERVER_ORIGIN,
  
  SENDER_EMAIL,
  SMTP_USER,
  SMTP_PASS,
  
  CLOUDINARY_CLOUD_NAME,
  CLOUDINARY_API_KEY,
  CLOUDINARY_API_SECRET,
  
  TEST_USER,
  TEST_PASS,
  
  PAYMENT_API_KEY,
  
  SEED_ADDRESSES,
  SEED_USERS,
  SEED_PRODUCTS,
  SEED_ORDERS,
  SEED_ORDER_ITEMS,
  SEED_PAYMENTS,
  SEED_REVIEWS,
  SEED_CART_ITEMS,
  SEED_NOTIFICATIONS,
  SEED_EXPO_TOKENS,
  SEED_REFRESH_TOKENS,
  SEED_OTPs,
};